remote_theme: mmistakes/so-simple-theme
title: Simon the Sourcerer AB
description: Expert application development and Linux consulting
logo: images/logo.png

collections:
  experience:
    output: true

defaults:
  - scope:
      path: ""
      type: "experience"
    values:
      layout: "experience"
